'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { authFetch } from '../auth-fetch';
import { usePermissions } from '../permissions';
import { Panel, StatusChip, Table } from '../ui';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Product={id:string;sku:string;name:string;productType:string;unit:string};
type Warehouse={id:string;code:string;name:string};
type RecipeItem={componentProductId:string;quantityPerBatch:number;wastePct:number;componentProduct:{sku:string;name:string;unit:string}};
type Recipe={id:string;code:string;name:string;version:number;outputQtyPerBatch:number;outputProduct:{id:string;sku:string;name:string;unit:string};items:RecipeItem[]};
type ProductionComponent={id:string;productId:string;plannedQty:number;actualQty?:number|null;unitCost?:string|null;totalCost?:string|null;product:{sku:string;name:string;unit:string}};
type ProductionOrder={id:string;number:string;status:string;batchCount:number;plannedOutputQty:number;actualOutputQty?:number|null;totalCost?:string|null;createdAt:string;recipe:{name:string;outputProduct:{sku:string;name:string}};warehouse:{code:string;name:string};components:ProductionComponent[]};
type Page<T>={items:T[];nextCursor?:string|null};
async function call<T>(token:string,path:string,init?:RequestInit):Promise<T>{const r=await authFetch(`${API}${path}`,token,{...init,headers:{'Content-Type':'application/json',...(init?.headers??{})}});const b=await r.json();if(!r.ok)throw new Error(Array.isArray(b.message)?b.message.join(', '):b.message??`HTTP ${r.status}`);return b as T;}

export default function ManufacturingView({token}:{token:string}){
  const {canAll,identity}=usePermissions(token); const canManage=Boolean(identity?.roles.some(r=>['SUPER_ADMIN','OWNER','ADMIN','MANAGER','WAREHOUSE'].includes(r)))&&canAll('manufacturing.manage');
  const [products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]),[orders,setOrders]=useState<ProductionOrder[]>([]);const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [recipeForm,setRecipeForm]=useState({code:'',name:'',outputProductId:'',outputQtyPerBatch:1,notes:'',componentProductId:'',quantityPerBatch:1,wastePct:0});
  const [recipeItems,setRecipeItems]=useState<Array<{componentProductId:string;quantityPerBatch:number;wastePct:number}>>([]);
  const [orderForm,setOrderForm]=useState({recipeId:'',warehouseId:'',batchCount:1,notes:''});
  async function refresh(){try{const [p,w,r,o]=await Promise.all([call<Page<Product>>(token,'/products?limit=200'),call<Warehouse[]>(token,'/inventory/warehouses'),call<Page<Recipe>>(token,'/manufacturing/recipes?limit=200'),call<Page<ProductionOrder>>(token,'/manufacturing/orders?limit=200')]);setProducts(p.items.filter(x=>x.productType==='PHYSICAL'));setWarehouses(w);setRecipes(r.items);setOrders(o.items);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Manufacturing gagal dimuat.');}}
  useEffect(()=>{void refresh();},[token]);
  const componentOptions=useMemo(()=>products.filter(p=>p.id!==recipeForm.outputProductId&&!recipeItems.some(i=>i.componentProductId===p.id)),[products,recipeForm.outputProductId,recipeItems]);
  function addComponent(){if(!recipeForm.componentProductId)return;setRecipeItems(v=>[...v,{componentProductId:recipeForm.componentProductId,quantityPerBatch:Math.max(1,Math.floor(recipeForm.quantityPerBatch)),wastePct:Math.max(0,recipeForm.wastePct)}]);setRecipeForm(v=>({...v,componentProductId:'',quantityPerBatch:1,wastePct:0}));}
  async function createRecipe(e:FormEvent){e.preventDefault();if(!recipeItems.length){setMessage('Minimal satu bahan baku wajib ditambahkan.');return;}setBusy(true);try{await call(token,'/manufacturing/recipes',{method:'POST',body:JSON.stringify({code:recipeForm.code,name:recipeForm.name,outputProductId:recipeForm.outputProductId,outputQtyPerBatch:recipeForm.outputQtyPerBatch,notes:recipeForm.notes||undefined,items:recipeItems})});setRecipeForm({code:'',name:'',outputProductId:'',outputQtyPerBatch:1,notes:'',componentProductId:'',quantityPerBatch:1,wastePct:0});setRecipeItems([]);await refresh();setMessage('Versi resep/BOM dibuat.');}catch(e){setMessage(e instanceof Error?e.message:'Gagal membuat resep.');}finally{setBusy(false);}}
  async function createOrder(e:FormEvent){e.preventDefault();setBusy(true);try{await call(token,'/manufacturing/orders',{method:'POST',body:JSON.stringify({recipeId:orderForm.recipeId,warehouseId:orderForm.warehouseId,batchCount:orderForm.batchCount,notes:orderForm.notes||undefined})});setOrderForm(v=>({...v,batchCount:1,notes:''}));await refresh();setMessage('Production order dibuat.');}catch(e){setMessage(e instanceof Error?e.message:'Gagal membuat production order.');}finally{setBusy(false);}}
  async function action(id:string,kind:'release'|'start'|'complete'|'cancel'){setBusy(true);try{const body=kind==='complete'?JSON.stringify({}):kind==='cancel'?JSON.stringify({reason:'Dibatalkan operator melalui Admin.'}):'{}';await call(token,`/manufacturing/orders/${id}/${kind}`,{method:'POST',body});await refresh();setMessage(`Production order ${kind} berhasil.`);}catch(e){setMessage(e instanceof Error?e.message:`Gagal ${kind}.`);}finally{setBusy(false);}}
  return <section className="moduleStack">
    <section className="grid2">
      <Panel eyebrow="BOM / RECIPE" title="Resep produksi versioned" badge={`${recipes.length} aktif`}><form className="formStack" onSubmit={createRecipe}><div className="grid2"><label>Kode<input required value={recipeForm.code} onChange={e=>setRecipeForm({...recipeForm,code:e.target.value.toUpperCase()})}/></label><label>Nama<input required value={recipeForm.name} onChange={e=>setRecipeForm({...recipeForm,name:e.target.value})}/></label></div><label>Produk hasil<select required value={recipeForm.outputProductId} onChange={e=>setRecipeForm({...recipeForm,outputProductId:e.target.value})}><option value="">Pilih produk hasil</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Output per batch<input type="number" min="1" value={recipeForm.outputQtyPerBatch} onChange={e=>setRecipeForm({...recipeForm,outputQtyPerBatch:Math.max(1,Number(e.target.value)||1)})}/></label><div className="grid2"><label>Bahan<select value={recipeForm.componentProductId} onChange={e=>setRecipeForm({...recipeForm,componentProductId:e.target.value})}><option value="">Pilih bahan</option>{componentOptions.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Qty/batch<input type="number" min="1" value={recipeForm.quantityPerBatch} onChange={e=>setRecipeForm({...recipeForm,quantityPerBatch:Math.max(1,Number(e.target.value)||1)})}/></label></div><div className="grid2"><label>Waste %<input type="number" min="0" max="100" step="0.1" value={recipeForm.wastePct} onChange={e=>setRecipeForm({...recipeForm,wastePct:Number(e.target.value)||0})}/></label><button type="button" className="secondary" disabled={!recipeForm.componentProductId} onClick={addComponent}>Tambah bahan</button></div><Table head={['Bahan','Qty/batch','Waste','Aksi']} rows={recipeItems.map((i,index)=>{const p=products.find(x=>x.id===i.componentProductId);return [p?`${p.sku} · ${p.name}`:i.componentProductId,i.quantityPerBatch,`${i.wastePct}%`,<button type="button" className="secondary" onClick={()=>setRecipeItems(v=>v.filter((_,n)=>n!==index))}>Hapus</button>]})} empty="Belum ada bahan."/><label>Catatan<textarea value={recipeForm.notes} onChange={e=>setRecipeForm({...recipeForm,notes:e.target.value})}/></label>{canManage&&<button disabled={busy||!recipeItems.length}>Simpan versi BOM</button>}</form></Panel>
      <Panel eyebrow="PRODUCTION ORDER" title="Rencana & posting produksi" badge={`${orders.length} order`}><form className="formStack" onSubmit={createOrder}><label>Resep<select required value={orderForm.recipeId} onChange={e=>setOrderForm({...orderForm,recipeId:e.target.value})}><option value="">Pilih resep</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.code} v{r.version} · {r.name}</option>)}</select></label><label>Gudang<select required value={orderForm.warehouseId} onChange={e=>setOrderForm({...orderForm,warehouseId:e.target.value})}><option value="">Pilih gudang</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}</select></label><label>Jumlah batch<input type="number" min="1" value={orderForm.batchCount} onChange={e=>setOrderForm({...orderForm,batchCount:Math.max(1,Number(e.target.value)||1)})}/></label><label>Catatan<textarea value={orderForm.notes} onChange={e=>setOrderForm({...orderForm,notes:e.target.value})}/></label>{canManage&&<button disabled={busy}>Buat production order</button>}</form><p className="sectionHelp">Complete mengonsumsi bahan melalui inventory movement, menghasilkan finished goods, lalu posting WIP → Inventory melalui accounting core dalam satu transaksi serializable.</p></Panel>
    </section>
    <Panel eyebrow="ACTIVE PRODUCTION" title="Lifecycle produksi"><Table head={['Nomor','Resep / Output','Gudang','Status','Qty','Biaya','Aksi']} rows={orders.map(o=>[o.number,<><strong>{o.recipe.name}</strong><br/><small>{o.recipe.outputProduct.sku} · {o.recipe.outputProduct.name}</small></>,`${o.warehouse.code} · ${o.warehouse.name}`,<StatusChip status={o.status}/>,`${o.actualOutputQty??o.plannedOutputQty} / ${o.plannedOutputQty}`,o.totalCost?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR'}).format(Number(o.totalCost)):'-',canManage?<div className="rowActions">{o.status==='DRAFT'&&<button type="button" onClick={()=>void action(o.id,'release')}>Release</button>}{o.status==='RELEASED'&&<button type="button" onClick={()=>void action(o.id,'start')}>Mulai</button>}{o.status==='IN_PROGRESS'&&<button type="button" onClick={()=>void action(o.id,'complete')}>Complete & posting</button>}{['DRAFT','RELEASED'].includes(o.status)&&<button type="button" className="secondary" onClick={()=>void action(o.id,'cancel')}>Batal</button>}</div>:null])} empty="Belum ada production order."/></Panel>
    {message&&<div className="notice">{message}</div>}
  </section>;
}
