import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { readdirSync, readFileSync as readSync } from 'node:fs';
import { join } from 'node:path';
import { analysis, antiVacuityErrors } from './helpers/mutation-payload-parity.mjs';

const propsOf = analysis.propsOf;

const ROOT = new URL('../', import.meta.url).pathname;

// forbidNonWhitelisted (apps/api/src/main.ts:33) turns a payload key the DTO does not declare into
// a hard 400. A (method, path) parity audit cannot catch this: the route pair is byte-identical
// whether the body is right or wrong. That is why the class of bug the user reported in HR/Payroll
// — "pembaruan shift mengirim seluruh objek respons" — survived a green route audit.
//
// This suite is built on the TypeScript AST, not regex. A regex version of this same scan was
// written first and reported a fictional 239 missing forms, because DTO names bled onto the
// following method. The parser got right only after four defects were fixed, each of which had
// silently produced a clean or wrong result:
//
//   1. a decorated regex for DTO properties backtracked exponentially on @Transform(({ obj }) …)
//   2. `while (re.exec())` without the /g flag looped forever on the same index
//   3. a signature regex /\(([^)]*)\)/ cannot match a parameter list containing @Body()
//   4. DTO `extends` was ignored, so every inherited field looked like an unknown key
//
// Each one is guarded below by an anti-vacuity assertion rather than a comment.

test('the parser is not silently under-parsing', () => {
  assert.deepEqual(antiVacuityErrors, [], `parser under-parsed:\n${antiVacuityErrors.join('\n')}`);
  // Cross-check against the officially generated audit. POST-1A added branch-sync, POST-1B added
  // branch-continuity and branch-transfer, POST-1C added mobile-ops including the draft
  // supervision list, taking the total from 454/36 to 503/40. The supervisor-approval module
  // (status/approve/pin) and the cross-branch stock endpoint took it to 507/42.
  // config/p5-full-ui-root-audit.json is regenerated by `npm run audit:ui:domain-depth`, which reads
  // the same scanner, so the two must agree.
  //
  // Derived rather than hardcoded: a literal here had to be hand-bumped twice in one session, and
  // each bump is a chance to record a number nobody checked. Counting the decorators directly still
  // fails when a route is added, but it fails on the real count instead of a remembered one.
  const controllerDir = join(process.cwd(), 'apps/api/src');
  const actualHandlers = readdirSync(controllerDir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.controller.ts'))
    .reduce((sum, entry) => {
      const text = readSync(join(entry.parentPath, entry.name), 'utf8');
      return sum + (text.match(/@(Get|Post|Patch|Put|Delete)\(/g) ?? []).length;
    }, 0);
  assert.equal(analysis.routes.length, actualHandlers,
    `route count must match the handlers on disk (${actualHandlers}); regenerate config/p5-full-ui-root-audit.json`);
  assert.ok(analysis.sites.length >= 140, `only ${analysis.sites.length} UI mutation call sites found`);
  assert.ok(analysis.boundDto >= 150, `only ${analysis.boundDto} routes bound to a DTO`);
});

test('every UI mutation payload stays inside its controller DTO', () => {
  const offenders = analysis.findings.filter((f) => f.kind === 'KEY_OUTSIDE_DTO');
  assert.deepEqual(
    offenders.map((f) => `${f.method} ${f.route.file}:${f.route.line} (${f.route.dto}) sends [${f.extraKeys.join(', ')}]`),
    [],
    'these payload keys are not whitelisted by the DTO, so ValidationPipe rejects the request with 400',
  );
});

test('inherited DTO properties count as allowed, not as unknown keys', () => {
  // UpdateAttendancePolicyDto declares only isActive; the other nine come from
  // CreateAttendancePolicyDto. ForbidNonWhitelisted validates inherited properties, so the UI
  // sending them is correct. This test exists because getting it wrong produced three false
  // "will 400" findings that were never real.
  const policy = propsOf('UpdateAttendancePolicyDto');
  for (const inherited of ['code', 'name', 'allowedMethods', 'requirePhoto', 'requireLocation', 'requireLiveness']) {
    assert.ok(policy.has(inherited), `${inherited} must resolve through the parent DTO`);
  }
  // Every inherited DTO must resolve to its parent fields. POST-1C adds ListMobileDraftsQueryDto
  // on top of the shared pagination query; lock the actual inherited contract rather than a brittle
  // repository-wide count that changes whenever a legitimate DTO inheritance is added.
  const mobileDrafts = propsOf('ListMobileDraftsQueryDto');
  for (const inherited of ['limit', 'cursor']) {
    assert.ok(mobileDrafts.has(inherited), `${inherited} must resolve through ListMobileBindingsQueryDto`);
  }
  assert.ok(analysis.heritage.size >= 6, 'DTO heritage resolution unexpectedly shrank');
});

test('the maintenance completion payload matches CompleteMaintenanceDto exactly', () => {
  // Regression for a near-miss. `notes` looked like a defect because a `sed -n '78,85p'` window
  // stopped one line above it, so the field appeared absent from the DTO. It is present, and the
  // payload correctly sends it. This test now reads the DTO through the AST so a partial window
  // can never make that mistake again, and it fails loudly if the two sides ever really diverge.
  const declared = [...propsOf('CompleteMaintenanceDto')];
  for (const expected of ['actualCost', 'odometer', 'inspectionId', 'taxCodeId', 'paymentMode', 'completedAt', 'parts', 'notes']) {
    assert.ok(declared.includes(expected), `CompleteMaintenanceDto should declare ${expected}`);
  }
  assert.ok(!declared.includes('inspectionNotes'), 'sanity: the AST must not invent properties');

  const ui = fs.readFileSync(path.join(ROOT, 'apps/admin/app/modules/assets-fleet.tsx'), 'utf8');
  const call = /const payload = \{ actualCost:[\s\S]*?\};\s*await api\(`\/assets\/maintenance\/\$\{completeMaintenanceId\}\/complete`/.exec(ui);
  assert.ok(call, 'the complete-maintenance payload must still be visible to this test');
  const sent = [...new Set([...call[0].matchAll(/(?:^|[{,]\s*)([a-zA-Z]\w*)\s*:/g)].map((m) => m[1]))];
  for (const key of sent) {
    assert.ok(declared.includes(key), `payload sends "${key}" but CompleteMaintenanceDto does not declare it`);
  }
  // odometer is only sent when non-empty, via a conditional spread; assert the guard exists so
  // the field cannot silently become unconditional.
  assert.match(call[0], /completeForm\.odometer \? \{ odometer:/, 'odometer must stay conditional');
});

test('the scanner does not confuse a second declaration of the same name', () => {
  // assets-fleet.tsx has two `const payload`, one per form. Resolving by first match in the file
  // attributed the maintenance-completion call to the maintenance-PLAN body and invented a nine
  // field "will 400" finding. Only a declaration above the call site may be used.
  const ui = fs.readFileSync(path.join(ROOT, 'apps/admin/app/modules/assets-fleet.tsx'), 'utf8');
  const count = (ui.match(/const payload = \{/g) ?? []).length;
  assert.ok(count >= 2, 'fixture assumption: this file must still declare payload more than once');
  const sites = analysis.sites.filter((s) => s.file.endsWith('assets-fleet.tsx') && s.bodyKeys);
  assert.ok(sites.length >= 3, 'the resolved body sites must be visible, otherwise the scan proved nothing');
});
