ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "unitCode" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "unitQuantity" INTEGER;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "quantityFactor" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "sourceBarcode" TEXT;
