export const FEATURE_KEYS = {
  MULTI_BRANCH: 'multi_branch',
  MULTI_WAREHOUSE: 'multi_warehouse',
  PAYMENT_GATEWAY: 'payment_gateway',
  MARKETPLACE: 'marketplace',
  SHIPPING: 'shipping',
  WHATSAPP: 'whatsapp',
  CUSTOMER_APP: 'customer_app',
  POS_OFFLINE: 'pos_offline',
  BATCH_EXPIRY: 'batch_expiry',
  SERIAL_NUMBER: 'serial_number',
  LOYALTY: 'loyalty',
  ACCOUNTING_FULL: 'accounting_full',
  BANK_RECONCILIATION: 'bank_reconciliation',
  APPROVAL_WORKFLOW: 'approval_workflow',
  FORECASTING: 'forecasting',
  REORDER_SUGGESTIONS: 'reorder_suggestions',
  BUSINESS_INTELLIGENCE: 'business_intelligence',
  SCALE_INTEGRATION: 'scale_integration',
  THIRD_PARTY_API: 'third_party_api',
  STOCK_TRANSFER: 'stock_transfer',
  STOCK_OPNAME: 'stock_opname',
  SALES_RETURN: 'sales_return',
  PURCHASE_RETURN: 'purchase_return',
  HRIS: 'hris',
  ATTENDANCE: 'attendance',
  ATTENDANCE_GEOFENCE: 'attendance_geofence',
  ATTENDANCE_PHOTO: 'attendance_photo',
  BIOMETRIC_ATTENDANCE: 'biometric_attendance',
  PAYROLL: 'payroll',
  PAYROLL_TAX: 'payroll_tax',
  EMPLOYEE_PORTAL: 'employee_portal',
  TELEGRAM_PAYSLIP: 'telegram_payslip',
  WHATSAPP_PAYSLIP: 'whatsapp_payslip',
  SYSTEM_TAX: 'system_tax',
  FIXED_ASSETS: 'fixed_assets',
  FLEET_DELIVERY: 'fleet_delivery',
  QUALITY_INSPECTION: 'quality_inspection',
  GATE_PASS: 'gate_pass',
  OPERATIONS_AUTOMATION: 'operations_automation',
  FLEET_GPS: 'fleet_gps',
} as const;

export type FeatureKey = typeof FEATURE_KEYS[keyof typeof FEATURE_KEYS];
