'use client';

import { FormEvent, useEffect, useState } from 'react';
import { authFetch } from './auth-fetch';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Memo = { id:string; title:string; body:string; isPinned:boolean; archivedAt?:string|null; updatedAt:string };
type MemoPage = { items: Memo[]; pageInfo:{ nextCursor:string|null; hasMore:boolean } };

function operationKey(){return globalThis.crypto?.randomUUID?.() ?? `memo-${Date.now()}-${Math.random().toString(36).slice(2)}`;}

export default function StaffMemoWidget({token}:{token:string}){
  const [memos,setMemos]=useState<Memo[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[search,setSearch]=useState(''),[showArchived,setShowArchived]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function request<T>(path:string,init?:RequestInit){const r=await authFetch(`${API}${path}`,token,{...init,headers:{'Content-Type':'application/json',...(init?.headers??{})}});const data=await r.json();if(!r.ok)throw new Error(Array.isArray(data.message)?data.message.join(', '):data.message??'Permintaan memo gagal');return data as T;}
  async function load(){try{const q=new URLSearchParams({limit:'50'});if(search.trim())q.set('search',search.trim());if(showArchived)q.set('includeArchived','true');const page=await request<MemoPage>(`/staff-memos?${q}`);setMemos(page.items);}catch(e){setMessage(e instanceof Error?e.message:'Memo gagal dimuat.');}}
  useEffect(()=>{void load();},[token,showArchived]);
  async function submit(e:FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);try{if(editingId){await request(`/staff-memos/${editingId}`,{method:'PATCH',body:JSON.stringify({title,body})});setMessage('Memo diperbarui.');}else{await request('/staff-memos',{method:'POST',headers:{'Idempotency-Key':operationKey()},body:JSON.stringify({title,body})});setMessage('Memo tersimpan.');}setTitle('');setBody('');setEditingId(null);await load();}catch(e){setMessage(e instanceof Error?e.message:'Memo gagal disimpan.');}finally{setBusy(false);}}
  async function patch(memo:Memo,data:Record<string,unknown>){setBusy(true);try{await request(`/staff-memos/${memo.id}`,{method:'PATCH',body:JSON.stringify(data)});await load();}catch(e){setMessage(e instanceof Error?e.message:'Memo gagal diperbarui.');}finally{setBusy(false);}}
  function edit(memo:Memo){setEditingId(memo.id);setTitle(memo.title);setBody(memo.body);}
  return <details className="staffMemoWidget" data-staff-memo-surface="admin"><summary><strong>Memo saya</strong><span>{memos.filter(x=>!x.archivedAt).length} aktif</span></summary><div className="staffMemoBody"><form className="staffMemoForm" onSubmit={e=>void submit(e)}><label>Judul<input maxLength={160} required value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Catatan<textarea maxLength={4000} rows={3} value={body} onChange={e=>setBody(e.target.value)} /></label><div className="rowActions"><button disabled={busy}>{editingId?'Simpan perubahan':'Tambah memo'}</button>{editingId&&<button type="button" className="secondary" onClick={()=>{setEditingId(null);setTitle('');setBody('');}}>Batal</button>}</div></form><div className="staffMemoTools"><input aria-label="Cari memo" placeholder="Cari memo" value={search} onChange={e=>setSearch(e.target.value)} /><button type="button" className="secondary" onClick={()=>void load()}>Cari</button><label className="checkboxRow"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)} /> Tampilkan arsip</label></div><div className="staffMemoList">{memos.length===0&&<p className="mutedText">Belum ada memo pribadi di cabang ini.</p>}{memos.map(memo=><article key={memo.id} className={memo.archivedAt?'staffMemoCard archived':'staffMemoCard'}><div><strong>{memo.isPinned?'📌 ':''}{memo.title}</strong><small>{new Date(memo.updatedAt).toLocaleString('id-ID')}</small>{memo.body&&<p>{memo.body}</p>}</div><div className="rowActions"><button type="button" className="secondary" onClick={()=>edit(memo)} disabled={busy}>Edit</button><button type="button" className="secondary" onClick={()=>void patch(memo,{isPinned:!memo.isPinned})} disabled={busy}>{memo.isPinned?'Lepas pin':'Pin'}</button><button type="button" className="secondary" onClick={()=>void patch(memo,{archived:!memo.archivedAt})} disabled={busy}>{memo.archivedAt?'Pulihkan':'Arsipkan'}</button></div></article>)}</div>{message&&<div className="notice">{message}</div>}</div></details>;
}
