ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "variantId" TEXT;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "productUnitId" TEXT;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "unitCode" TEXT;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "unitQuantity" INTEGER;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "quantityFactor" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "purchaseUnitCost" DECIMAL(18,2);

ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "variantId" TEXT;
ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "productUnitId" TEXT;
ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "unitCode" TEXT;
ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "unitQuantity" INTEGER;
ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "damagedUnitQuantity" INTEGER;
ALTER TABLE "GoodsReceiptItem" ADD COLUMN IF NOT EXISTS "quantityFactor" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "variantId" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "productUnitId" TEXT;
